//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseSpacePlannerComponents.SpaceObjectLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XamlDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XamlDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HouseSpacePlannerComponents.SpaceObjectLibrary.XamlDictionary", typeof(XamlDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Canvas Width=&quot;50&quot; Height=&quot;50&quot;
        ///                        xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                        xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        ///    &lt;Rectangle Width=&quot;50&quot; Height=&quot;50&quot;  Fill=&quot;Brown&quot; Stroke=&quot;#FF000000&quot;  /&gt;
        ///  &lt;/Canvas&gt;.
        /// </summary>
        internal static string Xaml_Box {
            get {
                return ResourceManager.GetString("Xaml_Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Canvas Width=&quot;54.4&quot; Height=&quot;72&quot;
        ///                xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                 xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        ///    &lt;Rectangle Width=&quot;54.4&quot; Height=&quot;72&quot; Stroke=&quot;#FF000000&quot; Fill=&quot;Brown&quot; Canvas.Left=&quot;0.2&quot; /&gt;
        ///    &lt;Ellipse Width=&quot;23.2&quot; Height=&quot;13.6&quot;  Stroke=&quot;#FF000000&quot; Fill=&quot;#FFFFFFFF&quot; Canvas.Left=&quot;4.2&quot; Canvas.Top=&quot;1.8&quot; /&gt;
        ///    &lt;Ellipse Width=&quot;23.2&quot; Height=&quot;13.6&quot;  Stroke=&quot;#FF000000&quot; Fill=&quot;#FFFFFFFF&quot; Canvas.Top=&quot;1.6&quot; Canvas.Left=&quot;28.4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Xaml_KindBed {
            get {
                return ResourceManager.GetString("Xaml_KindBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Canvas Width=&quot;54.4&quot; Height=&quot;72&quot;
        ///             xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///              xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        ///    &lt;Rectangle Width=&quot;54.4&quot; Height=&quot;72&quot; Stroke=&quot;#FF000000&quot; Fill=&quot;Brown&quot; Canvas.Left=&quot;0.2&quot; /&gt;
        ///    &lt;Ellipse Width=&quot;23.2&quot; Height=&quot;13.6&quot;  Stroke=&quot;#FF000000&quot; Fill=&quot;#FFFFFFFF&quot; Canvas.Left=&quot;4.2&quot; Canvas.Top=&quot;1.8&quot; /&gt;
        ///    &lt;Ellipse Width=&quot;23.2&quot; Height=&quot;13.6&quot;  Stroke=&quot;#FF000000&quot; Fill=&quot;#FFFFFFFF&quot; Canvas.Top=&quot;1.6&quot; Canvas.Left=&quot;28.4&quot;/&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Xaml_QueenBed {
            get {
                return ResourceManager.GetString("Xaml_QueenBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Canvas Width=&quot;85.8&quot; Height=&quot;45.6&quot; xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;  xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        ///    &lt;Path Width=&quot;85.8&quot; Height=&quot;45.6&quot; Fill=&quot;Brown&quot; Stretch=&quot;Fill&quot; Stroke=&quot;#FF000000&quot; Data=&quot;M38.099998,50.900002 L46.099998,43.699999 57.299997,37.299997 70.099997,35.699996 93.299995,36.499998 106.09999,38.899998 122.89999,47.700001 122.9,80.300008 111.69999,73.100008 100.5,66.700006 88.499996,63.500005 77.299996,62.700004 64.499997,62.700004 53.299998 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Xaml_RoundDesk {
            get {
                return ResourceManager.GetString("Xaml_RoundDesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Canvas Width=&quot;50&quot; Height=&quot;50&quot;  xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;  xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        ///    &lt;Ellipse Width=&quot;50&quot; Height=&quot;50&quot;  Fill=&quot;Brown&quot; Stroke=&quot;#FF000000&quot;  /&gt;
        ///  &lt;/Canvas&gt;.
        /// </summary>
        internal static string Xaml_RoundTable {
            get {
                return ResourceManager.GetString("Xaml_RoundTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Canvas Width=&quot;85.8&quot; Height=&quot;45.6&quot;
        ///                xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                 xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        ///    &lt;Path Fill=&quot;Brown&quot; Stretch=&quot;Fill&quot; Stroke=&quot;#FF000000&quot; Data=&quot;M35.86649,35.396606 L45.166665,35.218702 56.980742,35.396606 70.012294,35.254313 93.228908,35.2187 106.42448,35.140352 122.03217,35.2187 122.14038,45.112012 106.64583,49.727468 91.764336,58.168493 89.323382,66.70795 75.898135,66.885852 63.693365,66.707944  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Xaml_TV {
            get {
                return ResourceManager.GetString("Xaml_TV", resourceCulture);
            }
        }
    }
}
